### ISSUE TITLE
add support to run a command after snippet is added

### ISSUE THREAD

**Issue by ctf0** [Gruntfuggly/auto-snippet#1]
is that possible ?

**Comment by Gruntfuggly** [comment]
What sort of command - do you mean a vscode command?

Running a command without arguments is possible. Can you give me an example so I have the right idea.

**Comment by ctf0** [comment]
for example using php, i was thinking of running a command to [generate the namespace](https://github.com/MehediDracula/PHP-Namespace-Resolver) to the file once its created

**Comment by Gruntfuggly** [comment]
OK - shouldn't be a problem.

**Comment by Gruntfuggly** [comment]
Implemented in the latest version. There is an example of usage in the README.md.

**Comment by ctf0** [comment]
awesome, many thanx

**Comment by ctf0** [comment]
btw instead of using `,` for commands, we can make it as an array which is easier to read, i can make a PR for it you want.

**Comment by Gruntfuggly** [comment]
I was going to make it an array, but I changed it to a string so that it could be modified through the settings GUI. But at that point, it applied to all the globs. I then moved the setting so that it could be specified for each glob, so it can't be modified through the GUI now. 

I'll change it to an array later today.

**Comment by Gruntfuggly** [comment]
Latest version uses an array instead of a comma separated list.
